const areaNum = {
    'Hubei': "Hubei",
    'Guangdong': "Guangdong",
    'Zhejiang': "Zhejiang",
    'Henan': "Henan",
    'Hunan': "Hunan",
    'Anhui': "Anhui",
    'Jiangxi': "Jiangxi",
    'Chongqing': "Chongqing",
    'Jiangsu': "Jiangsu",
    'Shandong': "Shandong",
    'Sichuan': "Sichuan",
    '11': "Beijing",
    '12': "Heilongjiang",
    '13': "Shanghai",
    '14': "Fujian",
    '15': "Shaanxi",
    '16': "Guangxi",
    '17': "Hebei",
    '18': "Yunnan",
    '19': "Hainan",
    '20': "Shanxi",
    '21': "Liaoning",
    '22': "Guizhou",
    '23': "Tianjin",
    '24': "Gansu",
    '25': "Jilin",
    '26': "Inner Mongolia",
    '27': "Ningxia",
    '28': "Xinjiang",
    '29': "Qinghai",
    '30': "Tibet",
}