const areaNum = {
    "Hubei": "Hubei",
    "Guangdong": "Guangdong",
    "Zhejiang": "Zhejiang",
    "Henan": "Henan",
    "Hunan": "Hunan",
    "Anhui": "Anhui",
    "Jiangxi": "Jiangxi",
    "Chongqing": "Chongqing",
    "Jiangsu": "Jiangsu",
    "Shandong": "Shandong",
    "Sichuan": "Sichuan",
    "Beijing": "Beijing",
    "Heilongjiang": "Heilongjiang",
    "Shanghai": "Shanghai",
    "Fujian": "Fujian",
    "Shaanxi": "Shaanxi",
    "Guangxi": "Guangxi",
    "Hebei": "Hebei",
    "Yunnan": "Yunnan",
    "Hainan": "Hainan",
    "Shanxi": "Shanxi",
    "Liaoning": "Liaoning",
    "Guizhou": "Guizhou",
    "Tianjin": "Tianjin",
    "Gansu": "Gansu",
    "Jilin": "Jilin",
    "InnerMongolia": "Inner Mongolia",
    "Ningxia": "Ningxia",
    "Xinjiang": "Xinjiang",
    "Qinghai": "Qinghai",
    "Tibet": "Tibet",
    "Singapore": "Singapore",
    "HongKong": "Hong Kong",
    "Japan": "Japan",
    "Thailand": "Thailand",
    "SouthKorea": "South Korea",
    "Taiwan": "Taiwan",
    "Germany": "Germany",
    "Malaysia": "Malaysia",
    "Macau": "Macau",
    "Vietnam": "Vietnam",
    "France": "France",
    "Australia": "Australia",
    "UnitedArabEmirates": "United Arab Emirates",
    "Canada": "Canada",
    "India": "India",
    "Italy": "Italy",
    "Philippines": "Philippines",
    "UK": "UK",
    "Russia": "Russia",
    "US": "US",
    "Belgium": "Belgium",
    "Cambodia": "Cambodia",
    "Finland": "Finland",
    "Nepal": "Nepal",
    "Spain": "Spain",
    "SriLanka": "Sri Lanka",
    "Sweden": "Sweden"
}

const areaList = [{ "name": "湖北", "eng": areaNum.Hubei },
{ "name": "广东", "eng": areaNum.Guangdong },
{ "name": "浙江", "eng": areaNum.Zhejiang },
{ "name": "河南", "eng": areaNum.Henan },
{ "name": "湖南", "eng": areaNum.Hunan },
{ "name": "安徽", "eng": areaNum.Anhui },
{ "name": "江西", "eng": areaNum.Jiangxi },
{ "name": "重庆", "eng": areaNum.Chongqing },
{ "name": "江苏", "eng": areaNum.Jiangsu },
{ "name": "山东", "eng": areaNum.Shandong },
{ "name": "四川", "eng": areaNum.Sichuan },
{ "name": "北京", "eng": areaNum.Beijing },
{ "name": "黑龙江", "eng": areaNum.Heilongjiang },
{ "name": "上海", "eng": areaNum.Shanghai },
{ "name": "福建", "eng": areaNum.Fujian },
{ "name": "陕西", "eng": areaNum.Shaanxi },
{ "name": "广西", "eng": areaNum.Guangxi },
{ "name": "河北", "eng": areaNum.Hebei },
{ "name": "云南", "eng": areaNum.Yunnan },
{ "name": "海南", "eng": areaNum.Hainan },
{ "name": "山西", "eng": areaNum.Shanxi },
{ "name": "辽宁", "eng": areaNum.Liaoning },
{ "name": "贵州", "eng": areaNum.Guizhou },
{ "name": "天津", "eng": areaNum.Tianjin },
{ "name": "甘肃", "eng": areaNum.Gansu },
{ "name": "吉林", "eng": areaNum.Jilin },
{ "name": "内蒙古", "eng": areaNum.InnerMongolia },
{ "name": "宁夏", "eng": areaNum.Ningxia },
{ "name": "新疆", "eng": areaNum.Xinjiang },
{ "name": "青海", "eng": areaNum.Qinghai },
{ "name": "西藏", "eng": areaNum.Tibet },
{ "name": "新加坡", "eng": areaNum.Singapore },
{ "name": "香港", "eng": areaNum.HongKong },
{ "name": "日本", "eng": areaNum.Japan },
{ "name": "泰国", "eng": areaNum.Thailand },
{ "name": "韩国", "eng": areaNum.SouthKorea },
{ "name": "台湾", "eng": areaNum.Taiwan },
{ "name": "德国", "eng": areaNum.Germany },
{ "name": "马来西亚", "eng": areaNum.Malaysia },
{ "name": "澳门", "eng": areaNum.Macau },
{ "name": "越南", "eng": areaNum.Vietnam },
{ "name": "法国", "eng": areaNum.France },
{ "name": "澳大利亚", "eng": areaNum.Australia },
{ "name": "阿联酋", "eng": areaNum.UnitedArabEmirates },
{ "name": "加拿大", "eng": areaNum.Canada },
{ "name": "印度", "eng": areaNum.India },
{ "name": "意大利", "eng": areaNum.Italy },
{ "name": "菲律宾", "eng": areaNum.Philippines },
{ "name": "英国", "eng": areaNum.UK },
{ "name": "俄罗斯", "eng": areaNum.Russia },
{ "name": "美国", "eng": areaNum.US },
{ "name": "比利时", "eng": areaNum.Belgium },
{ "name": "柬埔寨", "eng": areaNum.Cambodia },
{ "name": "芬兰", "eng": areaNum.Finland },
{ "name": "尼泊尔", "eng": areaNum.Nepal },
{ "name": "西班牙", "eng": areaNum.Spain },
{ "name": "斯里兰卡", "eng": areaNum.SriLanka },
{ "name": "瑞典", "eng": areaNum.Sweden }]

const countryNum = {
    "Others": "Others",
    "MainlandChina": "Mainland China",
    "Singapore": "Singapore",
    "HongKong": "Hong Kong",
    "Japan": "Japan",
    "Thailand": "Thailand",
    "SouthKorea": "South Korea",
    "Taiwan": "Taiwan",
    "Germany": "Germany",
    "Malaysia": "Malaysia",
    "Macau": "Macau",
    "Vietnam": "Vietnam",
    "France": "France",
    "Australia": "Australia",
    "UnitedArabEmirates": "United Arab Emirates",
    "Canada": "Canada",
    "India": "India",
    "Italy": "Italy",
    "Philippines": "Philippines",
    "UK": "UK",
    "Russia": "Russia",
    "US": "US",
    "Belgium": "Belgium",
    "Cambodia": "Cambodia",
    "Finland": "Finland",
    "Nepal": "Nepal",
    "Spain": "Spain",
    "SriLanka": "Sri Lanka",
    "Sweden": "Sweden"
}
const countryList = [
    { "name": "其他", "eng": countryNum.Others },
    { "name": "中国", "eng": countryNum.MainlandChina },
    { "name": "新加坡", "eng": countryNum.Singapore },
    { "name": "香港", "eng": countryNum.HongKong },
    { "name": "日本", "eng": countryNum.Japan },
    { "name": "泰国", "eng": countryNum.Thailand },
    { "name": "韩国", "eng": countryNum.SouthKorea },
    { "name": "台湾", "eng": countryNum.Taiwan },
    { "name": "德国", "eng": countryNum.Germany },
    { "name": "马来西亚", "eng": countryNum.Malaysia },
    { "name": "澳门", "eng": countryNum.Macau },
    { "name": "越南", "eng": countryNum.Vietnam },
    { "name": "法国", "eng": countryNum.France },
    { "name": "澳大利亚", "eng": countryNum.Australia },
    { "name": "阿联酋", "eng": countryNum.UnitedArabEmirates },
    { "name": "加拿大", "eng": countryNum.Canada },
    { "name": "印度", "eng": countryNum.India },
    { "name": "意大利", "eng": countryNum.Italy },
    { "name": "菲律宾", "eng": countryNum.Philippines },
    { "name": "英国", "eng": countryNum.UK },
    { "name": "俄罗斯", "eng": countryNum.Russia },
    { "name": "美国", "eng": countryNum.US },
    { "name": "比利时", "eng": countryNum.Belgium },
    { "name": "柬埔寨", "eng": countryNum.Cambodia },
    { "name": "芬兰", "eng": countryNum.Finland },
    { "name": "尼泊尔", "eng": countryNum.Nepal },
    { "name": "西班牙", "eng": countryNum.Spain },
    { "name": "斯里兰卡", "eng": countryNum.SriLanka },
    { "name": "瑞典", "eng": countryNum.Sweden }]

export default { areaList, countryList };